name: Generate

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  base:
    name: Prepare base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Checkout Core repository
        uses: actions/checkout@v3.5.3
        with:
          repository: home-assistant/core
          path: core

      - name: Set up Python 3.13
        uses: actions/setup-python@v4.9.1
        with:
          python-version: 3.13.6

      - name: Create Python virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Create output dir
        run: mkdir output

      - name: Setup
        run: |
          . venv/bin/activate
          python src/setup.py

      - name: Collect manifest attributes
        run: |
          . venv/bin/activate
          python src/manifest.py

      - name: Collect code features
        run: |
          . venv/bin/activate
          python src/code_features.py

      - name: Collect test features
        run: |
          . venv/bin/activate
          python src/test_features.py

      - name: Collect AST features
        run: |
          . venv/bin/activate
          python src/python_ast.py

      - name: Collect usage info
        run: |
          . venv/bin/activate
          wget https://analytics.home-assistant.io/data.json
          python src/usage.py

      - name: Collect Translation stats
        run: |
          . venv/bin/activate
          python src/translations.py

      - name: Collect Integration Translation stats
        run: |
          . venv/bin/activate
          python src/integration_translations.py

      - name: Combine and publish to Google sheets
        run: |
          . venv/bin/activate
          python src/combine.py
        env:
          SHEET_KEY: ${{ secrets.SHEET_KEY }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: output/state.xlsx